# Site settings
title:       foldr me 0 universe #
email:       cxychina@gmail.com
author:      Xiaoyi Chen
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://xiaoyi.ch"

# Google analytics
google_analytics: UA-52076854-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: xiaoyi

# Social icons
github_username: xyc
stackoverflow_id:
twitter_username: chxy
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
kramdown:
  input: GFM
  coderay_line_numbers: nil
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
